doctrine:
    dbal:
        default_connection: General
        connections:
            General:
                override_url: true
                url: '%env(resolve:DATABASE_URL_GENERAL)%'
            Cliente:
                override_url: true
                url: '%env(resolve:DATABASE_URL_CLIENTE)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: General
        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        #auto_mapping: true
        entity_managers:
            General:
                connection: General
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings: 
                    General:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: General
            Cliente:
                connection: Cliente
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Cliente:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Cliente